bootstrap:
  src:
    src:001:sap:
      description: Description about sources related to name
      external_id: src:001:sap
    src:002:weather:
      description: Description about sources related to name
      external_id: src:002:weather

  in:
    in:001:trade:
      description: Description about user inputs related to name
      external_id: in:001:trade

  uc:
    uc:001:demand:
      description: Description about use case
      external_id: uc:001:demand
      shared_read_access:
        - src:001:sap
        - src:002:weather
      shared_owner_access:
        - in:001:trade
      metadata:
        created: 220401
        generated: by cdf-config-hub script

aad_mappings:
  cdf:root:
    - 374dc9f6-f3a1-4b34-b897-11111111111
    - CDF_DEV_ROOT
  cdf:allprojects:owner:
    - acd2fe35-aa51-45a7-acef-11111111111
    - CDF_DEV_ALLPROJECTS_OWNER
  cdf:allprojects:read:
    - acd2fe35-aa51-45a7-acef-0d54e2b6b6a8
    - CDF_DEV_ALLPROJECTS_READ
  cdf:uc:001:demand:read:
    - 314159-aa51-45a7-acef-11111111111
    - CDF_DEV_UC001DEMAND_READ

cognite:
  host: ${BOOTSTRAP_CDF_HOST}
  project: ${BOOTSTRAP_CDF_PROJECT}
  idp-authentication:
    client-id: ${BOOTSTRAP_IDP_CLIENT_ID}
    secret: ${BOOTSTRAP_IDP_CLIENT_SECRET}
    scopes:
      - ${BOOTSTRAP_IDP_SCOPES}
    token_url: ${BOOTSTRAP_IDP_TOKEN_URL}

logger:
  file:
    path: ./logs/create-dev-logs.log
    level: INFO
  console:
    level: INFO
