name: ci

on:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'image version (tag)'
  ## no automated run atm, only manual
  # push:
  #   branches:
  #     - main

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Version: ${{ inputs.version }}"
        echo "Skipping build on main branch"
