name: Check Quality and Test

on:
  pull_request:

env:
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: 1.3.2

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up cache
        uses: actions/cache@v3.2.5
        with:
          path: .venv
          key: venv-${{ hashFiles('poetry.lock') }}

      - name: Install Poetry ${{ env.POETRY_VERSION }}
        uses: cognitedata/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}

      - run: poetry install --sync

      - name: Run tests
        run: poetry run pytest

      - name: Run linting
        run: poetry run pre-commit run --all-files

      - name: Git diff (in case linting fails, prints why)
        if: always()
        run: git diff .

      - name: Run security checks
        run: poetry check
